### ISSUE TITLE
Cannot listen to photoswipe events

### ISSUE THREAD

**Issue by urbantrout** [GuoQichen/vue-pswipe#18]
The only event that shows up in the Vue devtools is `opened`. I try to listen for the `beforeChange` event like this:

```html
<photoswipe  @beforeChange="handleBeforeChange">
```

![Bildschirmfoto 2020-04-03 um 08 52 43](https://user-images.githubusercontent.com/10465787/78332537-84aaa780-7588-11ea-9877-6d1e94ae1460.png)

vue-pswipe version: 0.14.5

**Comment by GuoQichen** [comment]
https://codesandbox.io/s/gracious-morse-mqrbi
I tried it in CodeSandox and it works. Can you provide a recurring example?

**Comment by urbantrout** [comment]
I didn't manage to create a reproducable example on codesandbox. But what I figured out in the meantime is, that single word events like `close`, `destroy`, `resize` work. It seems that only camel-cased events are not working…

**Comment by urbantrout** [comment]
As a workaround this now works:

```
v-on="{beforeChange: handleBeforeChange}"
```

**Comment by GuoQichen** [comment]
OK. I will fix this bug soon.

**Comment by urbantrout** [comment]
I was using the photoswipe component in my HTML, not in a SFC.

**Comment by GuoQichen** [comment]
I figured it out. HTML tag and attributes are case insensitive. When using HTML directly. Vue uses el's outerHTML. So get `<photoswipe @beforechange="handleBeforeChange">`. 
Because the event is registered according to `vm.$listeners`, the event cannot be registered correctly.
I think using `<photoswipe v-on ="{ beforeChange: handleBeforeChange }">` is a trade-off, I will mark it in the document.
